### ISSUE TITLE
themes negate transparency

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#11]
affects linux
when changing theme to be anything other than classic, the transparency is not maintained
![image](https://github.com/DoubleDotStudios/Quartz/assets/96972638/dfbe85be-35fe-4a1f-83c7-71c5ccef330e)

**Comment by DoubleDotStudios** [comment]
After looking this bug persists on all devices. A fix will be rolled out with a future update.

**Comment by DoubleDotStudios** [comment]
This has been fixed with 1.1.1
