### ISSUE TITLE
Clicking the themes menu sometimes leads to it being unable to open

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#17]
Rarely, clicking the themes menu does does not lead to it appearing and the button becomes dysfunctional until the app is relaunched

affects: seemingly all (tested: windows v1.1.2-beta-1, v1.1.0 [linux] )

**Comment by DoubleDotStudios** [comment]
I believe this is an issue with the way the menu toggles. After testing, I found that if the menu does not pop up then clicking on it then away from it then then clicking it again sometimes fixes this. A fix should roll out soon.

**Comment by playerofceleste** [comment]
still affects v1.2.0 (appimg, arch linux)

**Comment by vaelixd** [comment]
Fixed in commit: 6e971b8
Sorry that the commit message does not mention this. Changes can be seen in the diffs.
Changes should be in effect from the next minor update.
