### ISSUE TITLE
[WINDOWS] Quartz continues to be borderless

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#20]
Quartz on windows is still borderless, even while the bug report claims otherwise

Affects: 1.1.2 beta 3

**Comment by DoubleDotStudios** [comment]
This is a mistake on my part. I changed the wrong parameter when attempting to fix a bug. I'm about to release a new beta.

**Comment by playerofceleste** [comment]
Affects 1.1.2 beta 3.5

**Comment by playerofceleste** [comment]
Duplicate issue
