### ISSUE TITLE
[WINDOWS] Fullscreening Quartz acts strangely

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#21]
Fullscreening Quartz using F11 acts strangely on windows
![image](https://github.com/DoubleDotStudios/Quartz/assets/96972638/633969a2-4f37-4fd5-931f-12c5d3bbd66e)
Affects: 1.1.2 beta 3

**Comment by DoubleDotStudios** [comment]
What does a regular window look like?

**Comment by playerofceleste** [comment]
![image](https://github.com/DoubleDotStudios/Quartz/assets/96972638/dcfa8b92-8d31-4324-a0e7-dbf639bcea84)

**Comment by playerofceleste** [comment]
![image](https://github.com/DoubleDotStudios/Quartz/assets/96972638/00a69fa9-9a26-4947-b9c7-6581e3a9b0e1)

**Comment by playerofceleste** [comment]
Affects 1.1.2 beta 3.5

**Comment by DoubleDotStudios** [comment]
This is now fixed with beta-3.5 r6.

**Comment by DoubleDotStudios** [comment]
This is now fixed with beta-3.5 r6.
