### ISSUE TITLE
no window decoration on cinnamon

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#26]
on cinnamon, quartz has no window decoration as it is not provided by the application

**Comment by nricciardi** [comment]
Same problem in OpenSUSE Tumbleweed KDE Plasma 6 (Wayland)

**Comment by playerofceleste** [comment]
> Same problem in OpenSUSE Tumbleweed KDE Plasma 6 (Wayland)

the issue is that the app doesn't supply window decor so it should affect any distribution / de(/wm) combo. this also, in-fact, affects windows as it too requires decor, the solution would obviously be to supply it. the reason this didn't come up earlier is due to me and DDoS testing for linux on a wm that doesn't have window decoration

**Comment by DoubleDotStudios** [comment]
Or origionally, me using macos where you can place the headlights for window control seperatly from the window bar/decor

**Comment by Saqr-Sayed** [comment]
yes that bug needs to be fixed. How I supposed to close the app? (I can with a shortcut but not all DEs users use shortcuts)

![image](https://github.com/user-attachments/assets/16757cdc-cc0e-4044-b3ad-b62106868a42)

**Comment by vaelixd** [comment]
Fixed with commit: 81d151b
Changes should be in effect from next minor update.
