### ISSUE TITLE
several typos in updated readme images

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#29]

**Comment by DoubleDotStudios** [comment]
I'm not sure where the typos are. Please highlight them so they can be fixed.

**Comment by playerofceleste** [comment]
raw fixed version (note: quartz should remain uncapitalised when beginning a sentence)

quartz
The aesthetically pleasing text editor.
Team:
Double Dot Studios: Developer and Maintainer
playerofceleste: Contributor and Linux Tester
Harrex: Contributor
IDK_XD: Windows Tester
quartz is designed with aesthetics in mind. It seamlessly integrates with your desktop setup to improve its looks. Write notes using Markdown or HTML tags.
If you don't know Markdown syntax or HTML tags, please visit [here] to learn.

**Comment by playerofceleste** [comment]
also there is no point including a link in an image, as the link cannot be used

**Comment by DoubleDotStudios** [comment]
a) thank you for pointing this out to me.
b) the link in the image is not for any functional use in the images. simply so that you can learn to use markdown one you have *quartz* should you want it.

**Comment by DoubleDotStudios** [comment]
The changes have been made but they won't be seen in the app until the next update which may take a few weeks.
