### ISSUE TITLE
Integration with NMD

### ISSUE THREAD

**Issue by nricciardi** [DoubleDotStudios/Quartz#30]
I have seen your videos about Quartz and I think that it is a cool text editor!

I haven't found your email to write this, I'm the creator of NMD (https://github.com/nricciardi/nmd) which is a new Markdown compiler written in Rust having some awesome features (in my point of view, obv).

I think that Quartz can be a nice editor for NMD, maybe we could work together to union Quartz and NMD.

**Comment by DoubleDotStudios** [comment]
I would love to try NMD but does it work with TS and electron since that's what *quartz* is built in and I don't have the time to rebuild it in rust.

**Comment by nricciardi** [comment]
NMD can be integrated using the CLI of NMD (already developed by me). In particular, we can compile the text acquired from Quartz editor and display the result (built with NMD).

**Comment by DoubleDotStudios** [comment]
Ok. I'm currently partaking in a game jam, however I'm interested in working on this with you after that. :)

**Comment by DoubleDotStudios** [comment]
Does NMD support html tags?

**Comment by DoubleDotStudios** [comment]
I will contact you by email and close this issue.
