### ISSUE TITLE
AppImage doesn't work on Wayland

### ISSUE THREAD

**Issue by nricciardi** [DoubleDotStudios/Quartz#31]
I have opened the AppImage of version `1.2.1` (last) using my OpenSUSE Tumbleweed with Wayland KDE Plasma 6 and Quartz wasn't shown correctly. In particular, the window bar is missed and it is too blurred.

**Comment by DoubleDotStudios** [comment]
This is similar to the issue to cinammon not having window decorations. Not just a wayland issue. Could you send a screenshot for clarity please.

**Comment by Saqr-Sayed** [comment]
> Could you send a screenshot for clarity please.

![Uploading image.png…]()

**Comment by Saqr-Sayed** [comment]
> Could you send a screenshot for clarity please.

![Screenshot From 2024-10-12 22-37-43](https://github.com/user-attachments/assets/a177173d-69e7-456e-b385-5ee7f8b881d4)

**Comment by vaelixd** [comment]
Fixed with commit: 81d151b
Changes should be seen in the next minor update.
