### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by moonlitgrace** [DoubleDotStudios/Quartz#32]
hi, it seems resources dir is missing from codebase.
`npm run dev` showin' this error:

```bash
 moonlitgrace@archlinux ~/..../Quartz  main  npm run dev

> quartz@1.2.1 dev
> electron-vite dev

vite v5.2.11 building SSR bundle for development...
✓ 1 modules transformed.
x Build failed in 76ms
 ERROR  Could not resolve "../../resources/icon.png?asset" from "src/main/index.ts"
file: /home/moonlitgrace/git/Quartz/src/main/index.ts
```

**Comment by DoubleDotStudios** [comment]
It's probably in the gitignore. Sorry, I'll add the directory to the repo.

**Comment by DoubleDotStudios** [comment]
Should be added now.

**Comment by moonlitgrace** [comment]
hi @DoubleDotStudios, It seems `resources` dir is still present in `.gitignore` file, you will prolly have to clear git cache.
that aside, good work, just i see some issues with wayland, will update you later.

**Comment by DoubleDotStudios** [comment]
I just forgot to push the changes to the gitignore. I’ll fix that now. The resources directory should be available though.
