### ISSUE TITLE
No minimum width or height

### ISSUE THREAD

**Issue by Saqr-Sayed** [DoubleDotStudios/Quartz#35]
Quartz window has No minimum width or height which causing the window to be just a line or a dot.
[Uploading Screencast From 2024-10-13 01-58-08.webm…]()

**Comment by Saqr-Sayed** [comment]
[Screencast From 2024-10-13 01-58-08.webm](https://github.com/user-attachments/assets/6353ddde-c61d-4ee2-b968-a98b179a629e)

**Comment by vaelixd** [comment]
Fixed with commit: 0f726f4
Changes should be seen with next minor update.
