### ISSUE TITLE
does not have a icon on GNOME, not in the AUR, not able to change font

### ISSUE THREAD

**Issue by Viyan1** [DoubleDotStudios/Quartz#37]
In Gnome, You can't see a icon of the Quartz app, and it is not available in the AUR
![2024-10-12_18-58](https://github.com/user-attachments/assets/6692748c-1c80-47f8-8b7a-39afe164e965)

**Comment by DoubleDotStudios** [comment]
Please use separate issues for things like this in the future. 

Not seeing the app icon is an issue across all Linux distros. 

Ability to change the font is a planned feature. 

Being in the AUR is planned and I’m currently working on that.
