### ISSUE TITLE
Hovering tools leads to overlap with other tools

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#8]
![image](https://github.com/DoubleDotGames/Quartz/assets/96972638/35ac90ec-1e62-4e5d-a588-6831399eb841)
Hovering over tools leads to an overlap with the other tool icons.
Suggested fix: Remove this text as there is already hover text, at least on my sys.
Affects: v1.0.0, possible: v1.0.1

**Comment by playerofceleste** [comment]
screenshot didnt seem to work 
![image](https://github.com/DoubleDotGames/Quartz/assets/96972638/35ac90ec-1e62-4e5d-a588-6831399eb841)
This version contains the issue

**Comment by playerofceleste** [comment]
Affects v1.0.1

**Comment by DoubleDotGames** [comment]
A fix for this issue will be released with the v1.0.2

**Comment by DoubleDotGames** [comment]
> Affects v1.0.1

It currently affects all versions of Quartz.

**Comment by DoubleDotStudios** [comment]
This has been fixed in v1.2.0 with the removal of buttons.
