### ISSUE TITLE
Italicised bolded text appears as bolded not both

### ISSUE THREAD

**Issue by playerofceleste** [DoubleDotStudios/Quartz#9]
Italicised bolded text appears as bolded not both

Expected result:
Bolding and italicising text leads to bold italic text

Observed:
Bolding and italicising text leads to bold text

**Comment by DoubleDotGames** [comment]
I'm currently looking into the issue. A fix should roll out with v1.0.2.

**Comment by DoubleDotStudios** [comment]
This has been fixed in v1.2.0
